### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by exotwd** [hammadshahir/php-mysql-ecommerce#13]
Hi! When im trying to connect to mysql database i have this error when inporting the sql file 
![image](https://user-images.githubusercontent.com/72092195/120096115-db2e5a00-c129-11eb-8f45-b889738927c2.png)
Anyone know how to fix it?

**Comment by exotwd** [comment]
And then on the page there is this error: 
![image](https://user-images.githubusercontent.com/72092195/120096533-51cc5700-c12c-11eb-9ead-5177a8515012.png)

**Comment by mhassanch** [comment]
table "tbl_settings" does not exit in database

**Comment by hammadshahir** [comment]
Please read instructions: 

 https://github.com/hammadshahir/PHP-MySQL-ecommerce-website/blob/master/DB%20Connection%20Settings.txt 

Also read Readme file.
