### ISSUE TITLE
Where is Blog page?

### ISSUE THREAD

**Issue by DanchoVENT** [hammadshahir/php-mysql-ecommerce#15]
Hello, where is the blog page, if isn't included how we should include it?

**Comment by Omar9820** [comment]
hi bro,
Did you get through with the customer registration?

**Comment by DanchoVENT** [comment]
I made a customer profile, and in admin panel i am registered with Super Admin.

**Comment by Omar9820** [comment]
How did you make a customer profile because for me i'm attempting to register as a customer i'm getting an error

**Comment by DanchoVENT** [comment]
What is the error?

**Comment by Omar9820** [comment]
This wasn't my error
My error was I can't get past the registration Everytime I'm registering I
get an error in the "country" tab
It's telling me to enter intergars and when I do no country pops up
So now that's my problem
I had posted it on GitHub under the username omar9820
Your help will be very much appreciated

**Comment by hammadshahir** [comment]
> Hello, where is the blog page, if isn't included how we should include it?

Yes, you can include it.
