### ISSUE TITLE
Issues #2

### ISSUE THREAD

**Issue by DanchoVENT** [hammadshahir/php-mysql-ecommerce#16]
There are no sections like "Testimonial" and "Blog" on the "index.php" page.
I activate them by removing the two slashes before ("$home_blog_on_off" and "$home_testimonial_on_off").

In this action, the 2 sections appear in the admin panel, but I can neither turn them on or turn them off.

It is clear to me that before making the section in "index.php", there is no way to show them to me.

My question is this. Are they made, and if so where can I find them to add them to the home page. Can I make a separate page just for the blog and not show it on the home page ?!

**Comment by hammadshahir** [comment]
You can call yourself those two sections. At the moment, this project is not maintained continously. But if you need help, you can let me know.
