### ISSUE TITLE
SQL Question

### ISSUE THREAD

**Issue by DanchoVENT** [hammadshahir/php-mysql-ecommerce#17]
Why in the database, all variables and non-variables are put in one table named "settings.php". 
What is the logic of this thing, because visually it is a complete mess.

Why in this table is added information about 32 different variables and non-variables, how it should be considered for each individual and different page.

**Comment by hammadshahir** [comment]
> Why in the database, all variables and non-variables are put in one table named "settings.php".
> What is the logic of this thing, because visually it is a complete mess.
> 
> Why in this table is added information about 32 different variables and non-variables, how it should be considered for each individual and different page.

That project was supposed to my college project so at that time, I really didn't care. lol. I am closing this issue on this note.
